{% set data = load_setup_py_data() %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  path: ..

build:
  noarch: python
  number: 0
  preserve_egg_dir: True
  script:
    - {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-build-isolation -vv

requirements:
  host:
    - python
    {% for dep in build_deps %}
    - {{ dep }}
    {% endfor  %}

  run:
    - python
    {% for dep in deps + conda_deps %}
    - {{ dep }}
    {% endfor %}
  
test:
  requires:
    {% for dep in test_deps %}
    - {{ dep }}
    {% endfor %}
  imports:
    - weatherdata
  source_files:
    - test/**

about:
  home: {{ home }}
  summary: {{ description }}
  license: {{ license }}

extra:
  recipe-maintainers:
    - pradal